### ISSUE TITLE
Switching between active windows breaks FFXIV main window focus

### ISSUE THREAD

**Issue by nolrinale** [Blooym/xlm#10]
While the game is running press the STEAM key and select the XIV launcher window, then, press the STEAM key again and select the main FFXIV window.

You will notice the window wont get focused properly, you wont be able to move your character anymore and theres no sound, the only way to fix this is closing the application entirely and starting from scratch. 

Tested with a standard Windows license, and running the game installed as FFXIV Free Trial

**Comment by Blooym** [comment]
Did this occur the way you ran FFXIV before? (If you did, that is)

**Comment by nolrinale** [comment]
I don't remember.... the last time i installed via the old xiv launcher method was months ago..... I just happened to test it today by chance and noticed this weird behavior

**Comment by Blooym** [comment]
I'm unable to replicate this in the way you described however I do notice that sometimes the game fails to realise it's been focused again 

I think this is a SteamOS / Wine problem and not related to XLM itself though

**Comment by Blooym** [comment]
Seems to be a wider issue outside of XLM so I'm gonna close this for now. If I can verify XLM causes it in the future I'll reopen & patch it accordingly
