### ISSUE TITLE
Frequent crashes with steamdeck autoinstaller

### ISSUE THREAD

**Issue by electr0sheep** [Blooym/xlm#11]
I experience crashes fairly frequently. I don't really have any reason to suspect the XLM compatibility tool. Sometimes it crashes directly back to steam, other times a wine error appears first. My first thought was to figure out a way to use GE Proton as an additional compatibility layer https://github.com/GloriousEggroll/proton-ge-custom. I figured I'd create an issue before I get too far down the rabbit hole to see if anyone has any advice.

**Comment by Blooym** [comment]
There should be log files in `~/.xlcore/logs` for Dalamud and Wine that can lead you in the right direction

**Comment by electr0sheep** [comment]
I didn't see anything really in the log files. However, I'm very convinced the troubles are plugin related and specific to running in wine. Sorry for the trouble.
