### ISSUE TITLE
Unable to enter any text at XIVLauncher login screen on Steam Deck

### ISSUE THREAD

**Issue by submatrix** [Blooym/xlm#12]
I am unable to input any text at the XIVLauncher login screen after performing the installation instructions as stated in the Readme. While my credentials are already stored in XIVLauncher and thus I don't strictly need to edit these fields, I have MFA on my account and thus need to input my OTP. After bringing up the steamOS keyboard with Steam+X (it doesn't pop up automatically when tapping on the text field) I am unable to input any numbers.

If I run XIVLauncher directly, which I separately installed following the instructions from https://goatcorp.github.io/faq/steamdeck.html, I am able to enter text, but this has a different issue that prevents me from using it as well.

**Comment by Blooym** [comment]
Are you running the launcher in gaming or desktop mode?

**Comment by submatrix** [comment]
> Are you running the launcher in gaming or desktop mode?

I am running in gaming mode.

**Comment by submatrix** [comment]
I'll add some more info for context. I didn't become aware of the existence of XLM until recently, so my steps for getting FFXIV installed were the following:

- Installed FFXIV under compatibility mode Proton Experimental
- Installed XIVLauncher, which installed another copy of FFXIV in ~/.xlcore
- Realizing my mistake, I uninstalled the standalone FFXIV install
- Installed XLM
- Added a non-Steam game pointing to ~/.xlcore/ffxiv/boot/ffxivboot.exe, with "Start in" pointing to ~/.xlcore/ffxiv/boot
- Changed the Compatibility tool of this non-Steam game to XLCore [XLM]
- Attemped to launch this non-Steam game from Gaming Mode.
- Unable to enter any text

**Comment by Blooym** [comment]
Okay I think I see where your problem is. 

XLM might not work properly if you add ffxivboot.exe as a non-steam game. Could you instead re-install FFXIV through Steam as this only installs the launcher and not the game twice, which is fine as it's only 1-2gb in size. Once you've done this, assign the XLM compatibility tool to FFXIV on Steam and launch again and let me know if it works

**Comment by submatrix** [comment]
> Could you instead re-install FFXIV through Steam as this only installs the launcher and not the game twice, which is fine as it's only 1-2gb in size.

Is this possible if I only have a Windows license of the game?

**Comment by Blooym** [comment]
> Is this possible if I only have a Windows license of the game?

Yes, just don't enable the Steam Service Account option. You can download the trial version of ffxiv from steam for free and just use that, it has no bearing on your license

**Comment by submatrix** [comment]
> > Is this possible if I only have a Windows license of the game?
> 
> Yes, just don't enable the Steam Service Account option. You can download the trial version of ffxiv from steam for free and just use that, it has no bearing on your license

This appears to have worked! I'm not sure where the Steam Service Account option is, but after launching the Trial version + XLM it prompted me for my OTP, then logged straight into the game. A few questions:

- Obviously, the game now thinks it's the trial version, so there is a "DEMO" badge on the cover art of the game. Is there any way to configure this?
- Is there an easy way to copy over my plugins from my Windows install to my Steam Deck install? By default there were no plugins installed after launching on Steam Deck.
- Is XLM somehow running the game from ~/.xlcore? In other words, do I need to keep XIVLauncher installed so that my FFXIV game files stored in ~/.xlcore are always present?

**Comment by Blooym** [comment]
> * Obviously, the game now thinks it's the trial version, so there is a "DEMO" badge on the cover art of the game. Is there any way to configure this?

I'm sure there are Steam Deck plugins that are able to change the cover art inside of Steam, but I'm not too knowledge about that, so you're best to look at up.

> * Is there an easy way to copy over my plugins from my Windows install to my Steam Deck install? By default there were no plugins installed after launching on Steam Deck.

You can copy plugin configuration files from `%appdata%\XIVLauncher\pluginConfigs` to `~/.xlcore/pluginConfigs`, however you must reinstall your plugins manually.

> * Is XLM somehow running the game from ~/.xlcore? In other words, do I need to keep XIVLauncher installed so that my FFXIV game files stored in ~/.xlcore are always present?

XLM stores data in `~/.xlcore`, please do not remove it unless you wish to lose all your FFXIV-related data. Uninstalling via Steam does not do this.

**Comment by submatrix** [comment]
> > * Obviously, the game now thinks it's the trial version, so there is a "DEMO" badge on the cover art of the game. Is there any way to configure this?
> 
> I'm sure there are Steam Deck plugins that are able to change the cover art inside of Steam, but I'm not too knowledge about that, so you're best to look at up.

Thanks! What about the fact that it shows I am playing the Trial version to my Steam friends? Any tricks that might get around this?

**Comment by Blooym** [comment]
Unfortunately not with that one to my knowledge
