### ISSUE TITLE
Possible to keep both XIVLauncher and XIVLauncherCN on Steamdeck via xlm?

### ISSUE THREAD

**Issue by acebando** [Blooym/xlm#14]
Tried to install Steam compatibility tool for both XIVLauncher and XIVLauncherCN via xlm steamdeck command, but they just overwrite each other,and both of them shown as "XLCore [XLM]" in the “compatibility” tab,which means I have to run the install command every time switching between XIVLaucher XIVLauncherCN at the moment.

**Comment by Blooym** [comment]
Not sure if this is something I want to support within XLM itself, however it's easy to do via some 1-time manual editing. To get this working, try the following:

1. Install XLM via the XIVLauncherCN script.
2. Navigate to the steam compatibility tools folder at `~/.steam/root/compatibilitytools.d/` and rename the `XLM` folder to`XLM_CN`. 
3. Open the folder and then open the `compatibilitytool.vdf` file, replace everything with this:
```
"compatibilitytools"
{
  "compat_tools"
  {
    "xlmcn" // Internal name of this tool
    {
      // Can register this tool with Steam in two ways:
      //
      // - The tool can be placed as a subdirectory in compatibilitytools.d, in which case this
      //   should be '.'
      //
      // - This manifest can be placed directly in compatibilitytools.d, in which case this should
      //   be the relative or absolute path to the tool's dist directory.
      "install_path" "."

      // For this template, we're going to substitute the display_name key in here, e.g.:
      "display_name" "XLCoreCN [XLM]"

      "from_oslist"  "windows"
      "to_oslist"    "linux"
    }
  }
}
```
4. Save the file and close it out.
5. Run the global XLM install script as normal. You do not need to make any modifications to it.

With this steam should offer you both as independent compatibility tool options, thus making it so you don't have to reinstall when switching.

![image](https://github.com/user-attachments/assets/c5b54077-be3a-4d34-96c2-ac3eca38a974)

**Comment by Blooym** [comment]
@Bluefissure If this is a common request it might be ideal to add this to the ottercorp docs page. This could also theoretically be done in the install script as well if you'd like

**Comment by Bluefissure** [comment]
> @Bluefissure If this is a common request it might be ideal to add this to the ottercorp docs page. This could also theoretically be done in the install script as well if you'd like

I may update my install scripts later, thank you!

**Comment by Bluefissure** [comment]
Hi @acebando and @Blooym , I have updated my script to install it as XLM_CN, you can run the [same script](https://file.bluefissure.com/FFXIV/Dalamud/xlcore/xlm/install-steamdeck-cn.sh) again to automatically does that.

I also turned off the xlm update check as it needs accessing github, and I'll keep a mirror under https://file.bluefissure.com/FFXIV/Dalamud/xlcore/xlm/releases

**Comment by acebando** [comment]
Thank you very much. It works now :)
