### ISSUE TITLE
What is the recommended update method?

### ISSUE THREAD

**Issue by kyuzumaki** [Blooym/xlm#17]
Thank you for this tool!

Was just wondering  how should upgrades be done is just re-running the command enough or does it self update?

May be worth adding whatever procedure is recommended to the readme.

**Comment by Blooym** [comment]
XLM will automatically download a new version on startup and replace the old one automatically unless disabled

I can document this by the install section

**Comment by Blooym** [comment]
Documented ae596d8bbf49928ce30603d126a8be183c5bd033
