### ISSUE TITLE
Incorrect install location for Linux Mint with Steam System Package

### ISSUE THREAD

**Issue by novice-coding-butterfly** [Blooym/xlm#20]
For Linux Mint 22 Cinnamon 6.2.9 (Steam installed via System package)
Steam's location for compatibility tools is
home/username/.steam/debian-installation/compatibilitytools.d

Not a major issue, since the file could easily be moved. But I figured I would mention it.

**Comment by Blooym** [comment]
Huh, I did not know Steam decided to move its installation directly on some systems? Does `~/.steam/root` exist for you?
